name: C/C++ CI

on:
  push:    
  pull_request:    

jobs:
    compile:
        name: Compile Repo with dependencies
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: miguelzamoram/v_tamp
                options: -v ${{ github.workspace }}:/home/tamp/24-data-gen/
                run: |
                    export FCL_PATH=/home/fcl/build
                    cd /home/tamp/
                    git clone https://github.com/vhartman/rai-manip.git 
                    git clone https://github.com/vhartman/rai-robotModels.git
                    git clone https://github.com/vhartman/rai.git rai-fork 
                    cd /home/tamp/rai-fork 
                    git checkout changes
                    echo "Building rai"
                    make
                    echo "Building 24-data-gen"
                    cd /home/tamp/24-data-gen/
                    make                    
                    mkdir ./out/
                    echo "Running keyframe tests"
                    ./x.exe -mode benchmark_single_keyframe > ./out/pick_and_place_keyframe.txt
                    tail -n 2 ./out/pick_and_place_keyframe.txt
                    ./x.exe -mode benchmark_handover > ./out/handover_keyframe.txt
                    tail -n 2 ./out/handover_keyframe.txt
                    ./x.exe -mode benchmark_pick_pick > ./out/pick_pick_keyframe.txt
                    tail -n 2 ./out/pick_pick_keyframe.txt
                    echo "Running planning tests"
                    echo "Repeated pick planning"
                    ./x.exe -mode benchmark_pick_pick_planning -verbosity 5 > ./out/pick_pick_planning.txt
                    tail -n 2 ./out/pick_pick_planning.txt
                    echo "Generic planning"
                    ./x.exe -mode benchmark_planning -verbosity 5 > ./out/dual_arm_planning.txt
                    tail -n 2 ./out/dual_arm_planning.txt
          - name: Archive keyframe computation results
            uses: actions/upload-artifact@v4
            with:
              name: Keyframes
              path: |
                out
